CONTAINER_NAME: default

# Parameter PHP_VERSION accepted values: 7.4, 7.2
PHP_VERSION: 7.4
# Parameter MYSQL_VERSION accepted values: 8.0, 5.7, 5.6
MYSQL_VERSION: 8.0

# General containers
INSTALL_REDIS: false
INSTALL_SUPERVISOR: false
INSTALL_PHP_FPM: true
INSTALL_NGINX: true
INSTALL_MYSQL: true

# Server settings
NGINX_ROOT_DIR: /var/www
