CONTAINER_NAME: default

# General containers
INSTALL_REDIS: false
INSTALL_SUPERVISOR: false
INSTALL_LARAVEL_HORIZON: false
INSTALL_MAILDEV: false
INSTALL_BEANSTALKD: false
INSTALL_PHP_FPM: true
INSTALL_NGINX: true
INSTALL_MYSQL: true

# Server settings
WORKSPACE_ENABLE_CRONTAB: true
NGINX_ROOT_DIR: /var/www

# Service versions
PHP_VERSION: 8.1    # accepted values: 7.2, 7.4, 8.0, 8.1
MYSQL_VERSION: 8.0
