- name: 'Create environment'
  hosts: localhost
  tasks:
    - name: 'Include config.yml vars'
      include_vars:
        file: ./../../config.yml
    - name: 'Include global vars'
      include_vars:
        dir: ./../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../vars/{{ env }}
    # Remove temp files
    - name: 'Remove workspace crontab file'
      file:
        path: ./../../services/workspace/crontab/root
        state: absent
    - name: 'Remove temp services directory'
      file:
        path: ./../../temp/services
        state: absent
    # Install docker components
    - name: 'Create web server temp directory for configs'
      when: INSTALL_NGINX
      file:
        path: ./../../temp/services/nginx
        state: directory
    - name: 'Create web server config file'
      when: INSTALL_NGINX
      template:
        src: ./../templates/nginx/nginx.conf
        dest: ./../../temp/services/nginx/nginx.conf
        force: true
    - name: 'Create database temp directory for configs'
      when: INSTALL_MYSQL
      file:
        path: ./../../temp/services/mysql
        state: directory
    - name: 'Create database config file'
      when: INSTALL_MYSQL
      template:
        src: ./../templates/mysql/my.cnf
        dest: ./../../temp/services/mysql/my.cnf
        force: true
    - name: 'Create php-fpm temp directory for configs'
      when: INSTALL_PHP_FPM
      file:
        path: ./../../temp/services/php-fpm
        state: directory
    - name: 'Create php-fpm config file'
      when: INSTALL_PHP_FPM
      template:
        src: ./../templates/php-fpm/php.ini
        dest: ./../../temp/services/php-fpm/php.ini
        force: true
    - name: 'Create supervisor temp directory for configs'
      when: INSTALL_SUPERVISOR
      file:
        path: ./../../temp/services/supervisor
        state: directory
    - name: 'Create supervisor config file'
      when: INSTALL_SUPERVISOR
      template:
        src: ./../templates/supervisor/supervisor-worker.conf
        dest: ./../../temp/services/supervisor/supervisor-worker.conf
        force: true
    - name: 'Create laravel horizon temp directory for configs'
      when: INSTALL_LARAVEL_HORIZON
      file:
        path: ./../../temp/services/laravel-horizon
        state: directory
    - name: 'Create laravel horizon config file'
      when: INSTALL_LARAVEL_HORIZON
      template:
        src: ./../templates/laravel-horizon/laravel-horizon.conf
        dest: ./../../temp/services/laravel-horizon/laravel-horizon.conf
        force: true
    # Enable docker container sections
    - name: 'Create workspace crontab file'
      when: WORKSPACE_ENABLE_CRONTAB
      template:
        src: ./../templates/workspace/root
        dest: ./../../services/workspace/crontab/root
        force: true
    # Generate app files
    - name: 'Create docker .env file'
      template:
        src: ./../templates/app/docker.env
        dest: ./../../.env
        force: true
    - name: 'Create docker-compose.yml file in root folder'
      template:
        src: ./../templates/app/docker-compose.yml
        dest: ./../../docker-compose.yml
        force: true
